---
abstract: 'convert Pod to HTML like TOBYINK'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: TOBYINK-Pod-HTML
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  TOBYINK::Pod::HTML:
    file: lib/TOBYINK/Pod/HTML.pm
    version: 0.004
  TOBYINK::Pod::HTML::Helper:
    file: lib/TOBYINK/Pod/HTML.pm
    version: 0.004
recommends:
  HTML::HTML5::Writer: 0.201
  PPI::Document: 0
  PPI::HTML: 0
  Syntax::Highlight::Engine::Kate: 0
  Syntax::Highlight::RDF: 0
  XML::LibXML::PrettyPrint: 0
requires:
  HTML::HTML5::Parser: 0.208
  Moo: 1.000008
  XML::LibXML::QuerySelector: 0.003
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/TOBYINK-Pod-HTML/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=TOBYINK-Pod-HTML
  homepage: https://metacpan.org/release/TOBYINK-Pod-HTML
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-tobyink-pod-html
version: 0.004
x_provides_scripts:
  pod2html-tobyink:
    file: bin/pod2html-tobyink
